Edits to nucleation benchmark as proposed by Mancias et al 2022
usnistgov/pfhub pull request #1465
Opened 2022-11-16 14:54 UTC by joseam2

These edits to the nucleation benchmark problem stem from the new journal publication and presentation given at CHIMAD XIV in October of 2022 which can both be accessed below:

Paper:
https://doi.org/10.1007/s40192-022-00284-1
Mancias, J., Attari, V., Arróyave, R. et al. On the Effect of Nucleation Undercooling on Phase Transformation Kinetics. Integr Mater Manuf Innov (2022). 

Presentation:
https://speakerdeck.com/joseam2/potential-edits-to-the-nucleation-benchmark

The edits included are briefly explained below:
-Use periodic boundary conditions for parts 2 and 3
-Change critical radius (r*) in part 3 to r* = 1.0
-Calculate the avrami slope using a fitting range in the y-axis (log[-log{1-Y}]) in parts 2 and 3, the range -2 < log[-log{1-Y}] < 0
-Increase the amount of simulations to increase statistical accuracy in parts 2 and 3 from 5 to 10.

The edits in the file caused by the machine-specific python code are not necessary to be accepted (e.g. execution_count, image.png data, metadata). Therefore, all edits following line 1000 in the jupyter notebook are not necessary.

2022-11-16 18:43 UTC, tkphd commented
Hi @joseam2, thank you for the contribution! Looking very much forward to seeing this deployed.

For readability, can you visit the [GitHub-Flavored Markdown docs](https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) and edit the PR description so it renders more properly? Specifically, please insert a space after each hyphen intended as a bullet/list item, and wrap math expressions in `$` so they render as beautifully as possible. Thanks!

2022-11-17 10:13 UTC, joseam2 commented
> 

I have edited the PR description above so that it renders better! Sorry about that.

2022-11-17 13:14 UTC, tkphd requested changes
A few tweaks, but this looks great!

I've dropped the $P$ nomenclature, since the specification uses a lot of variables already and it sows uncertainty over "how many am I really supposed to do?"
Finite differencing codes may not be able to finish 10 iterations of Part (c) in any reasonable amount of time -- which is a valuable point to consider when choosing a code.

2022-11-17 13:14 UTC, tkphd commented on benchmarks/benchmark8.ipynb
> +    "The driving force is the same as Part (b): $\\Delta f=1/(3 \\sqrt{2})$, which corresponds to a critical radius or $r^*=1$. The initial radii are also kept the same at $r_0 = 2.2r^*$ and the boun
While we're amending this sentence, let's drop a quirk of grammar
```suggestion
    "The driving force is the same as Part (b): $\\Delta f=1/(3 \\sqrt{2})$, which corresponds to a critical radius $r^*=1$. The initial radii are also kept the same at $r_0 = 2.2r^*$ and the boundary conditions are periodic. \n",
```

2022-11-17 13:14 UTC, tkphd commented on benchmarks/benchmark8.ipynb
> +    "Again, $\\phi$ is set to unity in regions of overlaps of nuclei. The simulations are run up to times $t=600$, and repeated for four more random initial conditions.  The total free energy plot th
"four more" is based on $P=5$. Fix copy-paste error in the original.

```suggestion
    "Again, $\\phi$ is set to unity in regions of overlaps of nuclei. The simulation is performed up to times $t=600$, and then repeated for a total of ten (10) simulations for statistical significance. The total free energy, time evolution of the solid fraction $Y$, and discrete particle count $N$ are plotted as functions of time, and an Avrami plot is generated for each of the 10 runs.\n",
```

2022-11-17 16:40 UTC, joseam2 commented
That is a great point about the $P$ nomenclature, thank you. I have accepted all of your requested changes in github.

2022-11-23 18:18 UTC, wd15 commented
@tkphd, @joseam2

[Link to the notebook rendered as HTML](https://random-cat-1465.surge.sh/benchmarks/benchmark8.ipynb/)

2022-11-23 18:44 UTC, wd15 approved these changes

2022-11-25 11:08 UTC, joseam2 commented
@wd15 @tkphd Damien pointed out to me that there were issues in the Submission Guidelines section which reflected the original value of 5 simulations. Those values have been replaced with 10 simulations in each instance in that section. Sorry about that, my latest commit was made to rectify this.

2022-12-06 17:20 UTC, merged